### PR TITLE
Update documentation for installing standard stack

### PR DESCRIPTION
**Pull request by nam20485**
Installing the standard stack on a Windows 10 Pro laptop went smoothly, but a few minor updates to the documentation may make the process more understandable for future users. I added a brief description of the install stack and its components so the user understands what he/she is installing prior to going through the steps, as well as some links that I found useful to vendor documentation for the actual components. Please suggest any changes you would like to what I proposed.

Addresses issue #63.

### CODE REVIEW

**Comment by nam20485** [comment]
OK I can make those changes. So just move them out of the top-level README.md in to the Windows 10/WSL README.md... is that the location you mean when you say to move them "into the one for Windows 10 Pro?"

**Comment by znmeb** [comment]
Yep ... just put them all in the https://github.com/hackoregon/data-science-pet-containers/blob/master/win10pro-wsl-ubuntu-tools/README.md

**Comment by nam20485** [comment]
Requested changes submitted.

**Comment by znmeb** [comment]
Merged! Thanks!!

**Pull request merged**
